Repository Dirack/proSU, pull requests merged in 2020-04, with the labels that each got.

#3 Feature/issue/2
  .gitignore
  geomodel
  mensagemAjuda.sh
  mensagemErro.sh
  modelo.itf
Labels: enhancement

#11 Develop/1.0 - Programas geomodel e interfaceBuiler, testes automatizados e manuais
  .gitignore
  .travis.yml
  Makefile
  TDD/interfaceBuilder_tdd.sh
  TDD/tdd_lib.sh
  geomodel
  interfaceBuilder
  manuais/geomodel.1
  manuais/interfaceBuilder.1
  mensagemAjuda.sh
  mensagemErro.sh
  su_test_models/modelo.itf
  su_test_models/novoModelo.itf
  su_test_models/teste.itf
  su_test_models/uma.itf
  suinstall
Labels: enhancement

#16 Hotfix/readme
  README.md
  campovel_suavizado.png
Labels: bug

#17 Develop/1.0
  README.md
  campovel_suavizado.png
Labels: bug

#18 Reconfigura o ambiente de testes do travis CI
  .travis.yml
Labels: bug

#19 Develop/1.0
  .travis.yml
Labels: bug

#20 Teste gerar imagem eps de modelo Resolve #12
  TDD/geomodel_tdd.sh
Labels: enhancement

#21 Develop/1.0 testes do programa geomodel finalizados
  TDD/geomodel_tdd.sh
Labels: enhancement

#23 Documentation/issue/22
  .github/ISSUE_TEMPLATE/test_request.md
  manuais/geomodel.1
  manuais/interfaceBuilder.1
Labels: documentation

#24 Develop/1.0
  .github/ISSUE_TEMPLATE/test_request.md
  manuais/geomodel.1
  manuais/interfaceBuilder.1
Labels: documentation

#28 Add pasta IVA, contendo script atualizado de analise de velocidade
  IVA/README.md
  IVA/cmp_test.su
  IVA/iva.scr
  IVA/iva.sh
Labels: bug, enhancement

#29 Correção de bug issue #8
  IVA/README.md
  IVA/cmp_test.su
  IVA/iva.scr
  IVA/iva.sh
Labels: bug, enhancement

#35 Documentation/issue/30
  README.md
  logo.jpg
Labels: documentation

#36 Develop/1.0
  README.md
  logo.jpg
Labels: documentation

#39 Retira as referências ao relatório do README
  README.md
Labels: documentation
